
// ================================================================
// Mock Labs Data

import type { Lab } from "../Types/MarketPlace/Marketplace";

// ================================================================
export const MOCK_LABS: Lab[] = [
  {
    id: 'als-dental',
    name: 'ALS Dental Lab',
    shortCode: 'ALSD',
    location: '85 Great Portland Street',
    city: 'London',
    country: 'England',
    establishedYear: 2018,
    status: 'Active',
    rating: 5,
    reviewCount: 48,
    email: 'yuvaraj.ram@connect.com',
    website: 'www.alsdentallab.co.uk',
    restorationTypes: ['Ceramic', 'Fixed Restoration', 'Metal'],
    eta: '3–5 days',
    basePrice: 65,
    featured: true,
    tags: ['NHS', 'Digital', 'ISO Certified'],
    pricingRows: [
      { materialGroup: 'Ceramic', materialType: 'Zirconia', eta: '< 5 Days', caseType: 'ALL', minPrice: 65, maxPrice: 65 },
      { materialGroup: 'Ceramic', materialType: 'E.Max', eta: '5–7 Days', caseType: 'Posterior', minPrice: 80, maxPrice: 90 },
      { materialGroup: 'Metal', materialType: 'PFM', eta: '< 3 Days', caseType: 'Anterior', minPrice: 45, maxPrice: 55 },
      { materialGroup: 'Ceramic', materialType: 'Monolithic Zirconia', eta: '< 2 Days', caseType: 'ALL', minPrice: 95, maxPrice: 120 },
      { materialGroup: 'Resin', materialType: 'Temporary Crown', eta: 'Same Day', caseType: 'Single Unit', minPrice: 25, maxPrice: 30 },
    ],
    technology: {
      compatibleScanners: ['iTero', 'Medit'],
      cadCamSoftware: [],
      premiumMaterials: ['Ivoclar', 'Kuraray'],
      certifications: ['ISO 13485', 'CE Marked'],
      fileFormats: ['STL', 'PLY'],
    },
    operationalMetrics: { monthlyCapacity: 320, onTimeDelivery: 97, remakeRate: 2.1, totalTechnicians: 12, avgExperience: 8, cdtCertified: 75 },
    qualityMetrics: { remakeRate: 2.1, fitAccuracy: 98.5, shadeMatching: 96, satisfaction: 4.8, surveyResponses: 142 },
    turnaround: { standardTat: 5, rushTat: 2, onTimeRate: 97, note: 'Unlimited capacity via 24/7 operations with dedicated DSO support team available.' },
    pricing: { basePrice: 65, price50Plus: 58, price200Plus: 52, freeRemakes: true, remakeWindow: 'Within 30 days', shippingIncluded: true, shippingMethod: 'Royal Mail / DPD 2-day' },
    support: { portal24x7: true, accountManager: true, freeConsultations: true, chairsideSupport: true, responseTimeHours: 24 },
    partnership: { freeSampleAvailable: true, firstOrderDiscount: 0, discountCode: 'N/A', partnershipBenefits: ['Free case consultations with experienced technicians', 'Volume discounts available for high-volume practices', 'Dedicated DSO support team for multi-location practices'] },
  },
  {
    id: 'costech-md',
    name: 'CosTech MD Pilot',
    shortCode: 'CTM',
    location: 'Dering Way',
    city: 'Gravesend',
    country: 'England',
    establishedYear: 2016,
    status: 'Active',
    rating: 5,
    reviewCount: 31,
    email: 'info@costech.co.uk',
    website: 'costech.co.uk',
    restorationTypes: ['Ceramic', 'Implant Products'],
    eta: '5–7 days',
    basePrice: 72,
    featured: false,
    tags: ['Independent', 'Analog', 'Digital'],
    pricingRows: [
      { materialGroup: 'Ceramic', materialType: 'Zirconia', eta: '5–7 Days', caseType: 'ALL', minPrice: 72, maxPrice: 85 },
      { materialGroup: 'Implant', materialType: 'Crown on Implant', eta: '7–10 Days', caseType: 'Single', minPrice: 110, maxPrice: 140 },
    ],
    technology: { compatibleScanners: ['iTero', '3Shape', 'Cerec'], cadCamSoftware: ['3Shape Design Studio'], premiumMaterials: ['Ivoclar', 'GC'], certifications: ['ISO 13485'], fileFormats: ['STL', 'OBJ', 'PLY'] },
    operationalMetrics: { monthlyCapacity: 180, onTimeDelivery: 94, remakeRate: 3.2, totalTechnicians: 7, avgExperience: 12, cdtCertified: 85 },
    qualityMetrics: { remakeRate: 3.2, fitAccuracy: 96.2, shadeMatching: 94, satisfaction: 4.6, surveyResponses: 88 },
    turnaround: { standardTat: 7, rushTat: 3, onTimeRate: 94 },
    pricing: { basePrice: 72, price50Plus: 65, price200Plus: 59, freeRemakes: true, remakeWindow: 'Within 21 days', shippingIncluded: true, shippingMethod: 'Royal Mail Tracked' },
    support: { portal24x7: true, accountManager: false, freeConsultations: true, chairsideSupport: false, responseTimeHours: 48 },
    partnership: { freeSampleAvailable: false, firstOrderDiscount: 10, discountCode: 'FIRST10', partnershipBenefits: ['Volume discounts for high-volume practices', 'Priority queue for rush cases'] },
  },
  {
    id: 'dental-infinity-lab',
    name: 'Dental Infinity Lab',
    shortCode: 'DIL',
    location: 'Station Road',
    city: 'Loughton',
    country: 'England',
    establishedYear: 2014,
    status: 'Active',
    rating: 5,
    reviewCount: 67,
    email: 'lab@dentalinfinity.co.uk',
    restorationTypes: ['Ceramic', 'Orthodontics'],
    eta: '5–10 days',
    basePrice: 60,
    tags: ['NHS', 'Analog', 'Private'],
    pricingRows: [
      { materialGroup: 'Ceramic', materialType: 'Zirconia', eta: '5–7 Days', caseType: 'ALL', minPrice: 60, maxPrice: 70 },
      { materialGroup: 'Ortho', materialType: 'Retainer', eta: '5–10 Days', caseType: 'Upper / Lower', minPrice: 45, maxPrice: 55 },
    ],
    technology: { compatibleScanners: ['iTero', 'Planmeca'], cadCamSoftware: ['exocad'], premiumMaterials: ['Ivoclar'], certifications: ['ISO 13485', 'CE Marked', 'MHRA Registered'], fileFormats: ['STL'] },
    operationalMetrics: { monthlyCapacity: 450, onTimeDelivery: 98, remakeRate: 1.8, totalTechnicians: 18, avgExperience: 10, cdtCertified: 90 },
    qualityMetrics: { remakeRate: 1.8, fitAccuracy: 99.1, shadeMatching: 97, satisfaction: 4.9, surveyResponses: 312 },
    turnaround: { standardTat: 7, rushTat: 3, onTimeRate: 98 },
    pricing: { basePrice: 60, price50Plus: 54, price200Plus: 48, freeRemakes: true, remakeWindow: 'Within 30 days', shippingIncluded: true, shippingMethod: 'DPD Next Day' },
    support: { portal24x7: true, accountManager: true, freeConsultations: true, chairsideSupport: true, responseTimeHours: 12 },
    partnership: { freeSampleAvailable: true, firstOrderDiscount: 15, discountCode: 'DIL15', partnershipBenefits: ['Dedicated account manager from day one', 'Free case consultations with lead technician', 'Volume discounts from 50+ cases/month'] },
  },
  {
    id: 'mlc-lab',
    name: 'MLC LAB',
    shortCode: 'MLC',
    location: 'Poonamalee High Road',
    city: 'Chennai',
    country: 'India',
    establishedYear: 2010,
    status: 'Active',
    rating: 5,
    reviewCount: 22,
    email: 'orders@mlclab.in',
    restorationTypes: ['Full Arch Restoration', 'Prosthetics', 'PMMA & Temps'],
    eta: '7–14 days',
    basePrice: 35,
    tags: ['Private', 'Digital', 'Overseas'],
    pricingRows: [
      { materialGroup: 'Ceramic', materialType: 'Full Arch Zirconia', eta: '7–10 Days', caseType: 'Full Arch', minPrice: 280, maxPrice: 380 },
      { materialGroup: 'PMMA', materialType: 'Temp Full Arch', eta: '3–5 Days', caseType: 'Full Arch', minPrice: 120, maxPrice: 160 },
    ],
    technology: { compatibleScanners: ['Medit', '3Shape'], cadCamSoftware: ['3Shape Design Studio', 'Meshmixer'], premiumMaterials: ['Upcera', 'VITA'], certifications: ['ISO 13485'], fileFormats: ['STL', 'OBJ'] },
    operationalMetrics: { monthlyCapacity: 600, onTimeDelivery: 91, remakeRate: 4.5, totalTechnicians: 24, avgExperience: 9, cdtCertified: 40 },
    qualityMetrics: { remakeRate: 4.5, fitAccuracy: 94, shadeMatching: 92, satisfaction: 4.3, surveyResponses: 56 },
    turnaround: { standardTat: 10, rushTat: 5, onTimeRate: 91 },
    pricing: { basePrice: 35, price50Plus: 30, price200Plus: 26, freeRemakes: false, shippingIncluded: false },
    support: { portal24x7: false, accountManager: false, freeConsultations: false, chairsideSupport: false, responseTimeHours: 72 },
    partnership: { freeSampleAvailable: false, firstOrderDiscount: 5, discountCode: 'MLC5', partnershipBenefits: ['Competitive pricing for bulk orders'] },
  },
];

// ── Dropdown Option Lists ─────────────────────────────────────────────────────

export const WORKFLOW_OPTIONS = [
  { value: 'all', label: 'All Workflow' },
  { value: 'analog', label: 'Analog' },
  { value: 'digital', label: 'Digital' },
];

export const PRACTICE_OPTIONS = [
  { value: 'all', label: 'All Practices' },
  { value: 'nhs', label: 'NHS' },
  { value: 'independent', label: 'Independent' },
  { value: 'private', label: 'Private' },
];

export const PRODUCT_OPTIONS = [
  { value: '', label: 'All Products' },
  { value: 'Additional Service', label: 'Additional Service' },
  { value: 'Appliances', label: 'Appliances' },
  { value: 'Appliances & Guards', label: 'Appliances & Guards' },
  { value: 'Ceramic', label: 'Ceramic' },
  { value: 'Fixed Restoration', label: 'Fixed Restoration' },
  { value: 'Full Arch Restoration', label: 'Full Arch Restoration' },
  { value: 'Implant Products', label: 'Implant Products' },
  { value: 'Models', label: 'Models' },
  { value: 'Orthodontics', label: 'Orthodontics' },
  { value: 'Overdenture Restoration', label: 'Overdenture Restoration' },
  { value: 'PMMA & Temps', label: 'PMMA & Temps' },
  { value: 'Porcelain Fused Metal', label: 'Porcelain Fused Metal / Full Cast / Partial Cast Metal' },
  { value: 'Prosthetics', label: 'Prosthetics' },
  { value: 'Removable Items', label: 'Removable Items' },
  { value: 'Surgical Guide', label: 'Surgical Guide' },
];